'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

export type Lang = 'en' | 'ar' | 'so'

export const translations = {
  en: {
    /* ── Nav ── */
    masjidName: 'Umatul Islam',
    masjidSub: 'Islamic Center of Minneapolis',
    masjidCity: 'Minneapolis, MN',
    navHome: 'Prayer Times',
    navEvents: 'Events',
    navAzkars: 'Azkars',
    navDonations: 'Donate',
    navAsk: 'Ask a Question',
    navDonateCta: 'Donate',
    navDonateMobile: 'Donate to the Masjid',
    /* ── Home ── */
    heroTitle: 'Umatul Islam',
    heroArabic: 'أُمَّةُ الإسْلَام',
    heroSub: 'Islamic Center of Minneapolis',
    dailySalah: 'Daily Salah',
    todayPrayers: "Today's Prayer Times",
    hijriDate: '9 Shawwal 1447 AH',
    adhan: 'Adhan',
    iqamah: 'Iqamah',
    currentPrayer: 'Current prayer',
    completed: 'Completed',
    upNext: 'Up next',
    nextLabel: 'Next',
    isnaBanner: 'ISNA METHOD · MINNEAPOLIS, MN · TIMES UPDATE DAILY',
    jumuahPrayerLabel: "Jumu'ah Prayer",
    jumuahBannerText: "Every Friday · Khutbah 1:00 PM · Salah 1:30 PM",
    jumuahAddressText: "2824 Lyndale Ave N — All welcome",
    /* ── Prayer Names ── */
    fajr: 'Fajr',
    sunrise: 'Sunrise',
    dhuhr: 'Dhuhr',
    asr: 'Asr',
    maghrib: 'Maghrib',
    isha: 'Isha',
    jummah: "Jumu'ah",
    jummahTime: "Khutbah: 1:00 PM · Prayer: 1:30 PM",
    /* ── About / Mission ── */
    aboutUsLabel: 'About Us',
    homeHeroTitle: 'Your Islamic Home Since 2001',
    homeDesc1: 'Umatul Islam Center is a mosque and Islamic community center serving Muslims of all backgrounds in Minneapolis and the greater Twin Cities area.',
    homeDesc2: 'We provide a welcoming space for daily worship, Islamic education, youth development, and community support. Our doors are always open — Muslim and non-Muslim alike.',
    statEstablished: 'Established',
    statNonprofit: 'Verified Nonprofit',
    statMethod: 'Prayer Method',
    statPrograms: 'Weekly Programs',
    testimonialText: '"This masjid has been my family\'s spiritual home for over a decade. The warmth and knowledge here is unmatched in the Twin Cities."',
    testimonialAuthor: '— Community Member, Minneapolis',
    announcementText: 'Youth Halaqah registration open for Summer 2026. Limited spots available.',
    registerLink: 'Register →',
    /* ── Programs ── */
    whatWeOffer: 'What We Offer',
    programsTitle: 'Programs & Services',
    programsDesc: 'Weekly programs for every member of the community — from children to elders.',
    prog1Title: 'Quranic Education',
    prog1Desc: 'Weekly Tajweed and memorization classes for children and adults of all levels.',
    prog2Title: "Women's Circle",
    prog2Desc: 'Sisters-only halaqah every Sunday. Quran, fiqh, and sisterhood.',
    prog3Title: 'Youth Halaqah',
    prog3Desc: 'Ages 13–25. Faith, identity, and purpose in America — every Saturday evening.',
    prog4Title: 'Community Support',
    prog4Desc: 'Food pantry, family assistance, and newcomer services for those in need.',
    learnMore: 'Learn more',
    /* ── Events section on home ── */
    communityLabel: 'Community',
    upcomingEvents: 'Upcoming Events',
    viewAllEvents: 'View all events →',
    /* ── Quran verse ── */
    verseIkhwa: '"The believers are but brothers."',
    /* ── Leadership ── */
    leadershipLabel: 'Leadership',
    leadershipTitle: 'Our Imam & Leadership',
    leadImam: 'Lead Imam',
    boardChair: 'Board Chair',
    religDirector: 'Religious Director',
    boardOfDir: 'Board of Directors',
    askImamLink: 'Ask the Imam a question →',
    /* ── Donation CTA ── */
    supportMasjidLabel: 'Support the Masjid',
    sustainTitle: 'Sustain Our Community',
    donationCtaDesc: 'Your donation keeps the masjid running and funds programs that serve hundreds of families. Even a small contribution is a',
    sadaqahJariyah: 'sadaqah jariyah',
    donationCtaDesc2: '— an ongoing act of worship.',
    donateNow: 'Donate Now',
    contactUs: 'Contact Us',
    sslEncrypted: 'SSL Encrypted',
    taxDeductible: 'Tax Deductible',
    allToMasjid: '100% to Masjid',
    /* ── Events page ── */
    eventsTitle: 'Upcoming Events',
    eventsSub: 'Stay connected with your community',
    eventsHeroTitle: 'Community Events',
    eventsHeroSub: 'Gather, learn, and grow together in faith and community',
    eventsHeroEyebrow: 'Umatul Islam Center · Minneapolis',
    tabAll: 'All Events',
    tabWeekly: 'Weekly',
    tabUpcoming: 'Upcoming',
    tabSpecial: 'Special',
    featuredLabel: 'Featured',
    allWelcome: 'All are welcome · No registration required',
    noEventsTitle: 'No events in this category',
    noEventsDesc: 'Check back soon or view all events.',
    verseHelp: '"Help one another in righteousness and piety." — Quran 5:2',
    /* ── Azkars ── */
    azkarsTitle: 'Daily Azkars',
    azkarsSub: 'Remembrance of Allah',
    tabMorning: 'Morning',
    tabEvening: 'Evening',
    tabAfterPrayer: 'After Prayer',
    repetitions: 'times',
    afterFajr: 'After Fajr',
    afterAsr: 'After Asr',
    everySalah: 'Every Salah',
    completeLabel: 'complete',
    sessionComplete: 'Session complete — JazakAllah Khair',
    doneLabel: 'Done',
    completeUpper: 'COMPLETE',
    virtueLabel: 'Virtue',
    verseRemember: '"Verily in the remembrance of Allah do hearts find rest." — Quran 13:28',
    verseRememberBottom: '"Remember Allah often so that you may succeed." — Quran 8:45',
    /* ── Donations ── */
    donateTitle: 'Support Your Masjid',
    donateSub: 'Your generosity keeps this community thriving',
    donateHeroSub: 'Your donation sustains our masjid, funds youth programs, and serves our community.',
    oneTime: 'One-time',
    monthly: 'Monthly',
    customAmount: 'Custom amount',
    yourName: 'Your Name (optional)',
    yourEmail: 'Email (optional)',
    submitDonation: 'Donate Now',
    sadaqahTitle: 'Sadaqah Jariyah',
    sadaqahDesc: 'Every donation to the masjid is an ongoing charity. When you give, Allah rewards you continuously — even after you pass.',
    donationNote: '* This is a demonstration form. Contact the masjid to donate.',
    whereMoneyGoes: 'Where Your Donation Goes',
    donArea1Title: 'Masjid Operations',
    donArea1Desc: 'Utilities, maintenance & upkeep',
    donArea2Title: 'Youth Programs',
    donArea2Desc: 'Quran classes & halaqah circles',
    donArea3Title: 'Community Aid',
    donArea3Desc: 'Families in need & local outreach',
    sadaqahJariyahTitle: 'Sadaqah Jariyah — Ongoing Reward',
    sadaqahJariyahDesc: 'When you donate to the masjid, the reward continues as long as it benefits the community. This is one of the most beloved forms of charity in Islam.',
    makeDonation: 'Make a Donation',
    secureDonation: 'Secure · Tax-deductible · 100% to the masjid',
    selectAmount: 'Select Amount',
    donatingLabel: 'Donating',
    donationReasonLabel: 'What is this donation for?',
    donationReasonOptional: '(optional)',
    donationReasonPlaceholder: 'e.g. Masjid renovation, in memory of…, general sadaqah',
    howToGive: 'How to Give',
    payCard: 'Pay by Card — Secured by Stripe',
    paypalDonation: 'PayPal Donation',
    sendViaZelle: 'Send via Zelle',
    sendViaCashApp: 'Send via Cash App',
    checkInPerson: 'Check or In-Person',
    selectMethodPrompt: 'Select a payment method above to continue',
    selectAmountPrompt: 'Select an amount above to continue',
    donationMayAllah: 'May Allah reward you with the best in this life and the next.',
    donateSecureSub: 'SSL Encrypted',
    donate501Sub: 'Tax Deductible',
    donateAllSub: 'Goes to Masjid',
    trustSecure: 'Secure',
    ongoingReward: 'ongoing reward',
    payCardSecured: 'Pay by Card — Secured by Stripe',
    stripeSSLNote: '256-bit SSL · Powered by Stripe',
    donateWithCard: 'Donate with Card',
    paypalGuestNote: 'Pay with your PayPal balance, bank, or any card. No account required — choose "Pay as Guest" on the next page.',
    donateViaPaypal: 'Donate via PayPal',
    paypalSecuredNote: 'Secured by PayPal',
    zelleInstructions: 'Open your bank app → Zelle → send to the info below. Instant and fee-free.',
    zelleMemoSuggest: 'add "Sadaqah" in the memo',
    cashInstructions: 'Open Cash App, tap the $ icon, and search the $cashtag below. Zero fees.',
    cashNoteSuggest: 'add "Sadaqah" in the note',
    sendAmount: 'Send',
    makePayableTo: 'Make Check Payable To',
    mailingAddressLabel: 'Mailing Address',
    envelopeNote: 'Donation envelopes are available at the masjid entrance during all prayer times.',
    methodCardLabel: 'Credit / Debit Card',
    methodCardSub: 'Visa · MC · Amex · Apple Pay',
    methodPaypalSub: 'Balance, bank, or card — no account required',
    methodZelleSub: 'Instant bank transfer — zero fees',
    methodCashSub: 'Send via $cashtag — zero fees',
    methodCheckLabel: 'Check / In-Person',
    methodCheckSub: 'Mail a check or drop it at the masjid',
    /* ── Ask ── */
    askTitle: 'Ask Leadership',
    askSub: 'Submit your question to our Imam or Board',
    questionLabel: 'Your Question',
    questionPlaceholder: 'Type your question here...',
    categoryLabel: 'Category',
    catFiqh: 'Islamic Ruling (Fiqh)',
    catCommunity: 'Community',
    catEvents: 'Events',
    catGeneral: 'General',
    nameLabel: 'Your Name',
    namePlaceholder: 'Enter your name',
    anonymousLabel: 'Submit anonymously',
    submitQuestion: 'Submit Question',
    confirmTitle: 'JazakAllah Khair!',
    confirmDesc: "Your question has been received. Our Imam will respond during the next Jumu'ah announcement or via email.",
    submitAnother: 'Submit Another Question',
    trustImamReviewed: 'Imam Reviewed',
    trustImamDesc: 'Every question read personally',
    trustAnonymous: '100% Anonymous',
    trustAnonDesc: 'Your identity stays private',
    trustResponse: 'Fri. Response',
    trustResponseDesc: "Addressed at Jumu'ah",
    faq1q: 'How long does it take to get a response?',
    faq1a: "Most questions are addressed at the following Jumu'ah Khutbah or within 3–5 business days privately by email if you provide contact info.",
    faq2q: 'Can I submit a question anonymously?',
    faq2a: 'Absolutely. Enable anonymous mode before submitting — your identity will never be shared with anyone, including the Imam.',
    faq3q: 'What kinds of questions can I ask?',
    faq3a: 'Any sincere Islamic question is welcome: fiqh (rulings), aqeedah (belief), family matters, community concerns, or general guidance. There are no "wrong" questions.',
    faq4q: 'Will my question be shared publicly?',
    faq4a: 'Only with your explicit permission. The Imam may use anonymized questions in Khutbah or educational content, but your personal information is never disclosed.',
    submitYourQuestion: 'Submit Your Question',
    allQuestionsReviewed: 'All questions reviewed with care',
    privacyLabel: 'Privacy',
    submitAnonymously: 'Submit anonymously',
    submittingAnon: 'Submitting anonymously',
    nameNotShared: 'Your name will NOT be shared',
    nameVisibleToImam: 'Your name is visible to the Imam only',
    emailAddressLabel: 'Email Address',
    emailOptionalDesc: '(optional — for a private reply)',
    emailPlaceholder: 'your@email.com',
    emailError: 'Please enter a valid email address.',
    questionReceived: 'Question Received',
    yourQuestionLabel: 'Your Question',
    submittedAnonymously: 'Submitted anonymously — your identity is fully protected',
    preferInPerson: 'Prefer to speak in person?',
    imamAvailable: "The Imam is available after Jumu'ah and Isha prayers.",
    reviewedByImam: 'Reviewed personally by the Imam. No personal data is shared or sold.',
    sendingQuestion: 'Sending your question…',
    /* ── Footer ── */
    footerQuickLinks: 'Quick Links',
    footerPrayerTimes: 'Prayer Times',
    footerContact: 'Contact',
    footerDesc: 'A welcoming Islamic community in the heart of Minneapolis, Minnesota.',
    footerApprox: '* Approximate · See homepage for live times',
    footerJumuahDesc: "Every Friday\nKhutbah 1:00 PM · Prayer 1:30 PM",
    footerCopyright: '© 2025 Umatul Islam Center · All Rights Reserved',
    footerPrivacy: 'Privacy Policy',
    footerAccessibility: 'Accessibility',
    /* ── General ── */
    loading: 'Loading...',
    footer: '© 2025 Umatul Islam · Minneapolis, MN · All rights reserved',
    islamicGuidance: 'Islamic Guidance',
    commonQuestions: 'Common Questions',
    announcement: 'Announcement',
    preferSpeakDesc: "The Imam is available after Jumu'ah and Isha prayers.",
  },

  ar: {
    masjidName: 'أمة الإسلام',
    masjidSub: 'المركز الإسلامي في مينيابوليس',
    masjidCity: 'مينيابوليس، مينيسوتا',
    navHome: 'أوقات الصلاة',
    navEvents: 'الفعاليات',
    navAzkars: 'الأذكار',
    navDonations: 'التبرع',
    navAsk: 'اسأل الإمام',
    navDonateCta: 'تبرع',
    navDonateMobile: 'تبرع للمسجد',
    heroTitle: 'أمة الإسلام',
    heroArabic: 'أُمَّةُ الإسْلَام',
    heroSub: 'المركز الإسلامي في مينيابوليس',
    dailySalah: 'الصلاة اليومية',
    todayPrayers: 'مواقيت الصلاة اليوم',
    hijriDate: '٩ شوال ١٤٤٧ هـ',
    adhan: 'الأذان',
    iqamah: 'الإقامة',
    currentPrayer: 'الصلاة الحالية',
    completed: 'مكتملة',
    upNext: 'التالية',
    nextLabel: 'التالي',
    isnaBanner: 'طريقة ISNA · مينيابوليس · تتحدث الأوقات يومياً',
    jumuahPrayerLabel: 'صلاة الجمعة',
    jumuahBannerText: 'كل جمعة · الخطبة ١:٠٠ م · الصلاة ١:٣٠ م',
    jumuahAddressText: '2824 Lyndale Ave N — الكل مرحب به',
    fajr: 'الفجر',
    sunrise: 'الشروق',
    dhuhr: 'الظهر',
    asr: 'العصر',
    maghrib: 'المغرب',
    isha: 'العشاء',
    jummah: 'صلاة الجمعة',
    jummahTime: 'الخطبة: ١:٠٠ م · الصلاة: ١:٣٠ م',
    aboutUsLabel: 'من نحن',
    homeHeroTitle: 'بيتك الإسلامي منذ عام ٢٠٠١',
    homeDesc1: 'مركز أمة الإسلام هو مسجد ومركز مجتمعي إسلامي يخدم مسلمي جميع الخلفيات في مينيابوليس ومنطقة المدن التوأم.',
    homeDesc2: 'نوفر مساحة ترحيبية للعبادة اليومية، والتعليم الإسلامي، وتنمية الشباب، ودعم المجتمع. أبوابنا مفتوحة دائماً — للمسلمين وغير المسلمين.',
    statEstablished: 'تأسست',
    statNonprofit: 'منظمة غير ربحية',
    statMethod: 'طريقة الصلاة',
    statPrograms: 'برامج أسبوعية',
    testimonialText: '"كان هذا المسجد بيتاً روحياً لعائلتي لأكثر من عقد. الدفء والمعرفة هنا لا مثيل لهما في المدن التوأم."',
    testimonialAuthor: '— عضو في المجتمع، مينيابوليس',
    announcementText: 'التسجيل في حلقة الشباب مفتوح لصيف ٢٠٢٦. الأماكن محدودة.',
    registerLink: 'سجّل →',
    whatWeOffer: 'ما نقدمه',
    programsTitle: 'البرامج والخدمات',
    programsDesc: 'برامج أسبوعية لكل فرد في المجتمع — من الأطفال إلى كبار السن.',
    prog1Title: 'التعليم القرآني',
    prog1Desc: 'دروس أسبوعية في التجويد والحفظ للأطفال والبالغين من جميع المستويات.',
    prog2Title: 'حلقة النساء',
    prog2Desc: 'حلقة للأخوات فقط كل أحد. القرآن والفقه والأخوة.',
    prog3Title: 'حلقة الشباب',
    prog3Desc: 'للأعمار من ١٣ إلى ٢٥. الإيمان والهوية والهدف في أمريكا — كل ليلة سبت.',
    prog4Title: 'دعم المجتمع',
    prog4Desc: 'مخزن غذائي ومساعدة الأسر وخدمات القادمين الجدد للمحتاجين.',
    learnMore: 'اقرأ المزيد',
    communityLabel: 'المجتمع',
    upcomingEvents: 'الفعاليات القادمة',
    viewAllEvents: 'عرض جميع الفعاليات →',
    verseIkhwa: '"إنما المؤمنون إخوة"',
    leadershipLabel: 'القيادة',
    leadershipTitle: 'إمامنا وقيادتنا',
    leadImam: 'الإمام الرئيسي',
    boardChair: 'رئيس مجلس الإدارة',
    religDirector: 'المدير الديني',
    boardOfDir: 'مجلس الإدارة',
    askImamLink: 'اسأل الإمام سؤالاً →',
    supportMasjidLabel: 'ادعم المسجد',
    sustainTitle: 'استدامة مجتمعنا',
    donationCtaDesc: 'تبرعك يبقي المسجد قائماً ويمول البرامج التي تخدم مئات الأسر. حتى مساهمة صغيرة هي',
    sadaqahJariyah: 'صدقة جارية',
    donationCtaDesc2: '— عبادة مستمرة.',
    donateNow: 'تبرع الآن',
    contactUs: 'اتصل بنا',
    sslEncrypted: 'مشفر بـ SSL',
    taxDeductible: 'معفى من الضرائب',
    allToMasjid: '١٠٠٪ للمسجد',
    eventsTitle: 'الفعاليات القادمة',
    eventsSub: 'ابقَ على تواصل مع مجتمعك',
    eventsHeroTitle: 'الفعاليات المجتمعية',
    eventsHeroSub: 'انضم إلينا في هذه الفعاليات المجتمعية',
    eventsHeroEyebrow: 'مركز أمة الإسلام · مينيابوليس',
    tabAll: 'كل الفعاليات',
    tabWeekly: 'أسبوعي',
    tabUpcoming: 'القادمة',
    tabSpecial: 'خاص',
    featuredLabel: 'مميز',
    allWelcome: 'الكل مرحب به · لا يشترط التسجيل',
    noEventsTitle: 'لا فعاليات في هذه الفئة',
    noEventsDesc: 'تحقق قريباً أو اعرض جميع الفعاليات.',
    verseHelp: '"تعاونوا على البر والتقوى" — القرآن ٥:٢',
    azkarsTitle: 'الأذكار اليومية',
    azkarsSub: 'ذكر الله تعالى',
    tabMorning: 'أذكار الصباح',
    tabEvening: 'أذكار المساء',
    tabAfterPrayer: 'أذكار بعد الصلاة',
    repetitions: 'مرة',
    afterFajr: 'بعد الفجر',
    afterAsr: 'بعد العصر',
    everySalah: 'كل صلاة',
    completeLabel: 'مكتمل',
    sessionComplete: 'اكتملت الجلسة — جزاك الله خيراً',
    doneLabel: 'تم',
    completeUpper: 'مكتمل',
    virtueLabel: 'الفضيلة',
    verseRemember: '"ألا بذكر الله تطمئن القلوب" — القرآن ١٣:٢٨',
    verseRememberBottom: '"واذكروا الله كثيراً لعلكم تفلحون" — القرآن ٨:٤٥',
    donateTitle: 'ادعم مسجدك',
    donateSub: 'كرمك يُبقي هذا المجتمع مزدهراً',
    donateHeroSub: 'تبرعك يُعين مسجدنا ويمول برامج الشباب ويخدم مجتمعنا.',
    oneTime: 'مرة واحدة',
    monthly: 'شهريًا',
    customAmount: 'مبلغ آخر',
    yourName: 'اسمك (اختياري)',
    yourEmail: 'البريد الإلكتروني (اختياري)',
    submitDonation: 'تبرّع الآن',
    sadaqahTitle: 'الصدقة الجارية',
    sadaqahDesc: 'كل تبرع للمسجد هو صدقة جارية. حين تعطي، يثيبك الله باستمرار — حتى بعد وفاتك.',
    donationNote: '* هذا نموذج تجريبي. تواصل مع المسجد للتبرع.',
    whereMoneyGoes: 'أين يذهب تبرعك',
    donArea1Title: 'عمليات المسجد',
    donArea1Desc: 'المرافق والصيانة والإشراف',
    donArea2Title: 'برامج الشباب',
    donArea2Desc: 'دروس القرآن وحلقات الدراسة',
    donArea3Title: 'المساعدات المجتمعية',
    donArea3Desc: 'الأسر المحتاجة والتوعية المحلية',
    sadaqahJariyahTitle: 'الصدقة الجارية — ثواب مستمر',
    sadaqahJariyahDesc: 'حين تتبرع للمسجد، يستمر الثواب طالما استفادت منه المجتمع. وهذا من أحب صور الصدقة في الإسلام.',
    makeDonation: 'أجرِ تبرعاً',
    secureDonation: 'آمن · معفى من الضرائب · ١٠٠٪ للمسجد',
    selectAmount: 'اختر المبلغ',
    donatingLabel: 'تبرع',
    donationReasonLabel: 'ما هذا التبرع؟',
    donationReasonOptional: '(اختياري)',
    donationReasonPlaceholder: 'مثال: تجديد المسجد، في ذكرى...، صدقة عامة',
    howToGive: 'كيف تتبرع',
    payCard: 'الدفع بالبطاقة — مؤمن بـ Stripe',
    paypalDonation: 'تبرع عبر PayPal',
    sendViaZelle: 'إرسال عبر Zelle',
    sendViaCashApp: 'إرسال عبر Cash App',
    checkInPerson: 'شيك أو شخصياً',
    selectMethodPrompt: 'اختر طريقة دفع أعلاه للمتابعة',
    selectAmountPrompt: 'اختر مبلغاً أعلاه للمتابعة',
    donationMayAllah: 'جزاك الله خيراً في الدنيا والآخرة.',
    donateSecureSub: 'مشفر بـ SSL',
    donate501Sub: 'معفى من الضرائب',
    donateAllSub: 'يذهب للمسجد',
    trustSecure: 'آمن',
    ongoingReward: 'ثواب مستمر',
    payCardSecured: 'الدفع بالبطاقة — مؤمن بـ Stripe',
    stripeSSLNote: '٢٥٦-بت SSL · بدعم Stripe',
    donateWithCard: 'تبرع بالبطاقة',
    paypalGuestNote: 'ادفع برصيد PayPal أو البنك أو أي بطاقة. لا يلزم حساب — اختر "ادفع كضيف" في الصفحة التالية.',
    donateViaPaypal: 'تبرع عبر PayPal',
    paypalSecuredNote: 'مؤمن بـ PayPal',
    zelleInstructions: 'افتح تطبيق بنكك → Zelle → أرسل إلى المعلومات أدناه. فوري ومجاني.',
    zelleMemoSuggest: 'أضف "صدقة" في الملاحظة',
    cashInstructions: 'افتح Cash App، اضغط على أيقونة $، وابحث عن الـ$cashtag أدناه. بلا رسوم.',
    cashNoteSuggest: 'أضف "صدقة" في الملاحظة',
    sendAmount: 'أرسل',
    makePayableTo: 'اجعل الشيك مدفوعاً لـ',
    mailingAddressLabel: 'عنوان البريد',
    envelopeNote: 'أظرف التبرع متاحة عند مدخل المسجد أثناء أوقات الصلاة.',
    methodCardLabel: 'بطاقة ائتمان / بطاقة خصم',
    methodCardSub: 'Visa · MC · Amex · Apple Pay',
    methodPaypalSub: 'الرصيد أو البنك أو البطاقة — لا يلزم حساب',
    methodZelleSub: 'تحويل بنكي فوري — بلا رسوم',
    methodCashSub: 'أرسل عبر $cashtag — بلا رسوم',
    methodCheckLabel: 'شيك / شخصياً',
    methodCheckSub: 'أرسل شيكاً بالبريد أو سلّمه في المسجد',
    askTitle: 'اسأل القيادة',
    askSub: 'أرسل سؤالك إلى الإمام أو مجلس الإدارة',
    questionLabel: 'سؤالك',
    questionPlaceholder: 'اكتب سؤالك هنا...',
    categoryLabel: 'التصنيف',
    catFiqh: 'حكم شرعي (فقه)',
    catCommunity: 'المجتمع',
    catEvents: 'الفعاليات',
    catGeneral: 'عام',
    nameLabel: 'اسمك',
    namePlaceholder: 'أدخل اسمك',
    anonymousLabel: 'إرسال بشكل مجهول',
    submitQuestion: 'إرسال السؤال',
    confirmTitle: 'جزاك الله خيراً!',
    confirmDesc: 'تم استلام سؤالك. سيجيب إمامنا في خطبة الجمعة القادمة أو عبر البريد الإلكتروني.',
    submitAnother: 'إرسال سؤال آخر',
    trustImamReviewed: 'مراجعة الإمام',
    trustImamDesc: 'كل سؤال يُقرأ شخصياً',
    trustAnonymous: '١٠٠٪ مجهول',
    trustAnonDesc: 'هويتك تبقى خاصة',
    trustResponse: 'رد الجمعة',
    trustResponseDesc: 'يُعالج في خطبة الجمعة',
    faq1q: 'كم يستغرق الرد؟',
    faq1a: 'تُعالج معظم الأسئلة في خطبة الجمعة التالية أو خلال ٣–٥ أيام عمل عبر البريد الإلكتروني إذا أتيت بمعلومات التواصل.',
    faq2q: 'هل يمكنني إرسال سؤال بشكل مجهول؟',
    faq2a: 'بالتأكيد. فعّل وضع الإخفاء قبل الإرسال — لن تتم مشاركة هويتك مع أي أحد، بما في ذلك الإمام.',
    faq3q: 'ما أنواع الأسئلة التي يمكنني طرحها؟',
    faq3a: 'أي سؤال إسلامي صادق مرحب به: الفقه، والعقيدة، والشؤون الأسرية، والهموم المجتمعية، أو التوجيه العام. لا توجد أسئلة "خاطئة".',
    faq4q: 'هل سيتم نشر سؤالي علناً؟',
    faq4a: 'فقط بإذنك الصريح. قد يستخدم الإمام أسئلة مجهولة الهوية في الخطبة أو المحتوى التعليمي، لكن معلوماتك الشخصية لن تُكشف أبداً.',
    submitYourQuestion: 'أرسل سؤالك',
    allQuestionsReviewed: 'جميع الأسئلة تُراجع بعناية',
    privacyLabel: 'الخصوصية',
    submitAnonymously: 'إرسال بشكل مجهول',
    submittingAnon: 'الإرسال بشكل مجهول',
    nameNotShared: 'لن يتم مشاركة اسمك',
    nameVisibleToImam: 'اسمك مرئي للإمام فقط',
    emailAddressLabel: 'البريد الإلكتروني',
    emailOptionalDesc: '(اختياري — للرد الخاص)',
    emailPlaceholder: 'your@email.com',
    emailError: 'يرجى إدخال عنوان بريد إلكتروني صحيح.',
    questionReceived: 'تم استلام السؤال',
    yourQuestionLabel: 'سؤالك',
    submittedAnonymously: 'أُرسل بشكل مجهول — هويتك محمية تماماً',
    preferInPerson: 'تفضل التحدث شخصياً؟',
    imamAvailable: 'الإمام متاح بعد صلاة الجمعة والعشاء.',
    reviewedByImam: 'يراجع الإمام شخصياً. لا يتم مشاركة البيانات الشخصية أو بيعها.',
    sendingQuestion: 'جار إرسال سؤالك…',
    footerQuickLinks: 'روابط سريعة',
    footerPrayerTimes: 'أوقات الصلاة',
    footerContact: 'التواصل',
    footerDesc: 'مجتمع إسلامي مرحّب به في قلب مينيابوليس، مينيسوتا.',
    footerApprox: '* تقريبي · انظر الصفحة الرئيسية للأوقات المباشرة',
    footerJumuahDesc: 'كل جمعة\nالخطبة ١:٠٠ م · الصلاة ١:٣٠ م',
    footerCopyright: '© ٢٠٢٥ أمة الإسلام · جميع الحقوق محفوظة',
    footerPrivacy: 'سياسة الخصوصية',
    footerAccessibility: 'إمكانية الوصول',
    loading: 'جار التحميل...',
    footer: '© ٢٠٢٥ أمة الإسلام · مينيابوليس، مينيسوتا · جميع الحقوق محفوظة',
    islamicGuidance: 'التوجيه الإسلامي',
    commonQuestions: 'أسئلة شائعة',
    announcement: 'إعلان',
    preferSpeakDesc: 'الإمام متاح بعد صلاة الجمعة والعشاء.',
  },

  so: {
    masjidName: 'Umatul Islam',
    masjidSub: 'Xarunta Islaamiga ee Minneapolis',
    masjidCity: 'Minneapolis, MN',
    navHome: 'Wakhtiyada Salaadda',
    navEvents: 'Xafladaha',
    navAzkars: 'Azkarta',
    navDonations: 'Deeq',
    navAsk: 'Su\'aal Weydii',
    navDonateCta: 'Deeq',
    navDonateMobile: 'Ku deeq Masaajidka',
    heroTitle: 'Umatul Islam',
    heroArabic: 'أُمَّةُ الإسْلَام',
    heroSub: 'Xarunta Islaamiga ee Minneapolis',
    dailySalah: 'Salaadda Maalinlaha ah',
    todayPrayers: 'Wakhtiyada Salaadda Maanta',
    hijriDate: '9 Shawwal 1447 AH',
    adhan: 'Adhaan',
    iqamah: 'Iqaamah',
    currentPrayer: 'Salaadda hadda',
    completed: 'Dhammaystay',
    upNext: 'Xiga',
    nextLabel: 'Xiga',
    isnaBanner: 'HABKA ISNA · MINNEAPOLIS, MN · WAKHTIYADU WAY CUSBOONAAN',
    jumuahPrayerLabel: "Salaadda Jumu'ah",
    jumuahBannerText: "Jimce kasta · Khudbo 1:00 GD · Salaad 1:30 GD",
    jumuahAddressText: "2824 Lyndale Ave N — Dhammaan baa soo dhawaynta",
    fajr: 'Fajr',
    sunrise: 'Qorraxda soo baxaysa',
    dhuhr: 'Dhuhr',
    asr: 'Casar',
    maghrib: 'Marib',
    isha: 'Cishe',
    jummah: "Jumu'ah",
    jummahTime: "Khudbo: 1:00 GD · Salaad: 1:30 GD",
    aboutUsLabel: 'Nagu saabsan',
    homeHeroTitle: 'Gurigaaga Islaamiga ah ee 2001 Ilaa',
    homeDesc1: 'Umatul Islam Center waa masaajid iyo xarun bulsheed islaamiyeed oo u adeegaysa Muslimiinta dhammaan asalkooda ah ee ku nool Minneapolis iyo agagaarka Twin Cities.',
    homeDesc2: 'Waxaan bixinaa goob soo dhaweynaysa salaadda maalinlaha ah, waxbarashada Islaamiga, horumarinta dhalinyarada, iyo taageerada bulshada. Albaabadeenu had iyo jeer waa furan yihiin — Muslimiin iyo kuwa aan Muslimiin ahayn labadaba.',
    statEstablished: 'La Aasaasay',
    statNonprofit: 'Ururin aan Faa\'idada Raadin',
    statMethod: 'Habka Salaadda',
    statPrograms: 'Barnaamijyo Todobaadlaha',
    testimonialText: '"Masaajidkani waxa uu ahaa gurigii ruuxiga ee qoyskaygii muddo ka badan toban sano. Kulaylka iyo aqoontu halkan ku jirta ma laha la midkeed Twin Cities."',
    testimonialAuthor: '— Xubin Bulsho, Minneapolis',
    announcementText: 'Diiwaangelinta Xalaqada Dhalinyarada waa furan tahay Xagaaga 2026. Meelaha ayaa xaddidan.',
    registerLink: 'Diiwaan geli →',
    whatWeOffer: 'Waxa Aannu Bixino',
    programsTitle: 'Barnaamijyada & Adeegyada',
    programsDesc: 'Barnaamijyo todobaadlaha ah oo loogu talagalay xubin kasta oo bulsho — carruurta ilaa odayaasha.',
    prog1Title: 'Barashada Quraanka',
    prog1Desc: 'Fasallada Tajweed iyo xifdhiga todobaadlaha ah loogu talagalay carruurta iyo dadka waaweyn dhammaan heerarka.',
    prog2Title: 'Xalaqada Haweenka',
    prog2Desc: 'Xalaqo kaliya ah oo haweenka ah Axad kasta. Quraanka, fiqhka, iyo walaaltinimada.',
    prog3Title: 'Xalaqada Dhalinyarada',
    prog3Desc: 'Jirka 13–25. Imaan, aqoonsi, iyo ujeeddo America — Sabtida kasta galabtii.',
    prog4Title: 'Taageerada Bulshada',
    prog4Desc: 'Kaydka cuntada, gargaarka qoysaska, iyo adeegyada cusub ee kuwa baahan.',
    learnMore: 'Wax badan baro',
    communityLabel: 'Bulshada',
    upcomingEvents: 'Xafladaha Soo Socda',
    viewAllEvents: 'Arag dhammaan xafladaha →',
    verseIkhwa: '"Mu\'miniinta waxay yihiin walaalaha"',
    leadershipLabel: 'Hoggaanka',
    leadershipTitle: 'Imaamkayaga & Hoggaankayaga',
    leadImam: 'Imaamka Hogaamiya',
    boardChair: 'Madaxa Golaha',
    religDirector: 'Agaasimaha Diiniga',
    boardOfDir: 'Golaha Maamulka',
    askImamLink: 'Imaamka su\'aal weydiiso →',
    supportMasjidLabel: 'Garab sii Masaajidka',
    sustainTitle: 'Dhaqaajinta Bulshadeena',
    donationCtaDesc: 'Deeqddaadu waxay masaajidka socodsiinaysaa oo ay maalgelisaa barnaamijyada u adeegaya boqollaal qoys. Xitaa tabaruc yar waxa weeye',
    sadaqahJariyah: 'sadaqah jariyah',
    donationCtaDesc2: '— cabuddhad joogto ah.',
    donateNow: 'Hadda Deeq',
    contactUs: 'Nala soo xiriir',
    sslEncrypted: 'SSL Koodhsan',
    taxDeductible: 'Canshuurta ka Jari Kara',
    allToMasjid: '100% Masaajidka',
    eventsTitle: 'Xafladaha Soo Socda',
    eventsSub: 'La xiriir bulshaddaada',
    eventsHeroTitle: 'Xafladaha Bulshada',
    eventsHeroSub: 'Is ku soo biir, baranow, oo wada kordhow rumaysadka iyo bulshada',
    eventsHeroEyebrow: 'Umatul Islam Center · Minneapolis',
    tabAll: 'Dhammaan Xafladaha',
    tabWeekly: 'Todobaadlaha',
    tabUpcoming: 'Soo Socda',
    tabSpecial: 'Gaara',
    featuredLabel: 'Mudan',
    allWelcome: 'Dhammaan baa soo dhawaynta · Diiwaangelinta looma baahna',
    noEventsTitle: 'Xaflado kuma jiraan qaybtan',
    noEventsDesc: 'Dib u eeg dhawaan ama arag dhammaan xafladaha.',
    verseHelp: '"Is kaalmeeya xushmada iyo taqdirta." — Quraanka 5:2',
    azkarsTitle: 'Azkarta Maalinlaha ah',
    azkarsSub: 'Xusuusta Alle',
    tabMorning: 'Subaxda',
    tabEvening: 'Fiidkii',
    tabAfterPrayer: 'Ka dib Salaadda',
    repetitions: 'jeer',
    afterFajr: 'Ka dib Fajrka',
    afterAsr: 'Ka dib Casarka',
    everySalah: 'Salaad kasta',
    completeLabel: 'dhammaystay',
    sessionComplete: 'Falanqayntu waa dhammaatay — JazakAllah Khair',
    doneLabel: 'Dhammaystay',
    completeUpper: 'DHAMMAYSTAY',
    virtueLabel: 'Fadliga',
    verseRemember: '"Xaqiiqdii xusuuska Alle ayaa qalbigu ku nasaada." — Quraanka 13:28',
    verseRememberBottom: '"Alle aad u xusuusna si aad u guulaystaan." — Quraanka 8:45',
    donateTitle: 'Garab sii Masaajidkaaga',
    donateSub: 'Karamigaagu bulshadan ayuu wanaajinayaa',
    donateHeroSub: 'Deeqddaadu waxay masaajidkeenna garab siinaysaa, barnaamijyada dhalinyarada maalgelisaa, oo bulshadeenna u adeegaysaa.',
    oneTime: 'Mar hal ah',
    monthly: 'Bishii',
    customAmount: 'Qaddar kale',
    yourName: 'Magacaaga (ikhtiyaari)',
    yourEmail: 'Emailka (ikhtiyaari)',
    submitDonation: 'Hadda Deeq',
    sadaqahTitle: 'Sadaqah Jariyah',
    sadaqahDesc: 'Deeq kasta oo masaajidka ah waa sadaqah jariyah. Marka aad bixiso, Alle wuu ku abaal marinayaa joogto — xitaa ka dib dhimashadaada.',
    donationNote: '* Tani waa foom tusaale ah. La xiriir masaajidka si aad u deeqdo.',
    whereMoneyGoes: 'Xagee Deeqddaadu Aadaysaa',
    donArea1Title: 'Hawlaha Masaajidka',
    donArea1Desc: 'Adeegyada, dayactirka & ilaalinta',
    donArea2Title: 'Barnaamijyada Dhalinyarada',
    donArea2Desc: 'Fasallada Quraanka & xalaqooyinka',
    donArea3Title: 'Gaargaar Bulshada',
    donArea3Desc: 'Qoysaska baahan & gaadhitaanka maxalliga',
    sadaqahJariyahTitle: 'Sadaqah Jariyah — Abaal Joogto ah',
    sadaqahJariyahDesc: 'Marka aad masaajidka u deeqdo, abaalku wuu sii socdaa ilaa bulshadu ka faa\'ido qaadatay. Tan waa mid ka mid ah qaababka ugu jecel sadaqa ee Islaamka.',
    makeDonation: 'Deeq samee',
    secureDonation: 'Ammaan · Canshuurta ka jari kara · 100% Masaajidka',
    selectAmount: 'Dooro Qadarka',
    donatingLabel: 'Deeq',
    donationReasonLabel: 'Deeqddani maxay u tahay?',
    donationReasonOptional: '(ikhtiyaari)',
    donationReasonPlaceholder: 'Tusaale: Dib u habeynta Masaajidka, xusuus..., sadaqo guud',
    howToGive: 'Sida Loo Deeqo',
    payCard: 'Ku bixi Kaarka — Stripe ayaa ammaan ilaalinayaa',
    paypalDonation: 'Deeq PayPal',
    sendViaZelle: 'U dir Zelle',
    sendViaCashApp: 'U dir Cash App',
    checkInPerson: 'Jeeg ama Si Toos ah',
    selectMethodPrompt: 'Dooro habka lacag bixinta ee kor u muuqda si aad u sii socoto',
    selectAmountPrompt: 'Dooro qadarka kor u muuqda si aad u sii socoto',
    donationMayAllah: 'Alle haa ku abaalmariyo kan ugu wanaagsan adduunka iyo aakhirada.',
    donateSecureSub: 'SSL Koodhsan',
    donate501Sub: 'Canshuurta ka jari kara',
    donateAllSub: 'Masaajidka u taga',
    trustSecure: 'Ammaan',
    ongoingReward: 'abaal joogto ah',
    payCardSecured: 'Ku bixi Kaarka — Stripe ayaa ammaan ilaalinayaa',
    stripeSSLNote: '256-bit SSL · Stripe ayaa taageeraya',
    donateWithCard: 'Kaarka ku deeq',
    paypalGuestNote: 'Ku bixi PayPal, bangiga, ama kaarka. Akoon looma baahna — "Martida Ahaan Bixi" dooro bogga ku xiga.',
    donateViaPaypal: 'PayPal iyada oo loo marinayo deeqo',
    paypalSecuredNote: 'PayPal ayaa ammaan ilaalinayaa',
    zelleInstructions: 'Fur abka bangigaaga → Zelle → u dir macluumaadka hoose. Degdeg ah oo bilaash ah.',
    zelleMemoSuggest: '"Sadaqo" ku dar xusuusta',
    cashInstructions: 'Fur Cash App, taab summada $, uguna raadi $cashtag-ka hoose. Bilaash.',
    cashNoteSuggest: '"Sadaqo" ku dar xusuusta',
    sendAmount: 'Dir',
    makePayableTo: 'Jeegga u dhig',
    mailingAddressLabel: 'Cinwaanka Boostada',
    envelopeNote: 'Envelopeyada deeqda ayaa laga heli karaa xafiiska masaajidka wakhtiyada salaadda oo dhan.',
    methodCardLabel: 'Kaarka Deynta / Debit',
    methodCardSub: 'Visa · MC · Amex · Apple Pay',
    methodPaypalSub: 'Xisaabta, bangiga, ama kaarka — akoon looma baahna',
    methodZelleSub: 'Wareejin bangi ah oo degdeg ah — bilaash',
    methodCashSub: '$cashtag iyada oo loo marinayo dir — bilaash',
    methodCheckLabel: 'Jeeg / Si Toos ah',
    methodCheckSub: 'Boostada ku dir jeeg ama masaajidka keenso',
    askTitle: 'Hoggaanka Weydii',
    askSub: 'Su\'aashaada u soo dir Imaamka ama Golaha',
    questionLabel: 'Su\'aashaada',
    questionPlaceholder: 'Halkan ku qor su\'aashaada...',
    categoryLabel: 'Qaybta',
    catFiqh: 'Xukun Diini (Fiqh)',
    catCommunity: 'Bulshada',
    catEvents: 'Xafladaha',
    catGeneral: 'Guud',
    nameLabel: 'Magacaaga',
    namePlaceholder: 'Geli magacaaga',
    anonymousLabel: 'Si qarsoodi ah u soo dir',
    submitQuestion: 'Soo dir Su\'aasha',
    confirmTitle: 'JazakAllah Khair!',
    confirmDesc: "Su\'aashaadu waa la helay. Imaamku wuxuu ka jawaabi doonaa Jumu'ah xigta ama emailka.",
    submitAnother: 'Su\'aal kale soo dir',
    trustImamReviewed: 'Imaamku dib u eegaa',
    trustImamDesc: 'Su\'aal kasta si shakhsi ah ayaa loo aqriyaa',
    trustAnonymous: '100% Qarinsan',
    trustAnonDesc: 'Aqoonsigaagu wuu gaaban yahay',
    trustResponse: "Jawaab Jimcaha",
    trustResponseDesc: "Lagu xaliyaa Jumu'ah",
    faq1q: 'Intee in le\'eg ayay qaadanaysaa jawaabta helida?',
    faq1a: "Inta badan su\'aalaha waxaa lagu xaliyaa Jumu'ah xigta ama 3–5 maalmood shaqo gudahood si qarsoodi ah emailka haddaad xog xiriir bixiso.",
    faq2q: 'Ma soo diri karaa su\'aal si qarsoodi ah?',
    faq2a: 'Haa. Xiddiga qarsoodi-ka shid kahor diridda — aqoonsigaaga weligiis lama wadaagi doono cidna, Imaamka oo kale.',
    faq3q: 'Nooca su\'aalaha maxaan weydiin karaa?',
    faq3a: 'Su\'aal kasta oo Islaamiga ah oo daacad ah baa soo dhawaynta: fiqhka, caqiidada, arrimaha qoyska, dhibaatooyinka bulshada, ama hagida guud. Ma jirto su\'aal "khaldan".',
    faq4q: 'Ma la wadaagi doonaa su\'aashayda dadweynaha?',
    faq4a: 'Ogolaanshahaaga keliya. Imaamku wuxuu isticmaali karaa su\'aalaha la qariyay Xutbada ama waxbarasho, laakiin xogta shakhsigaaga weligeed lama muujin doono.',
    submitYourQuestion: 'Soo dir Su\'aashaada',
    allQuestionsReviewed: 'Dhammaan su\'aalaha si taxadir leh ayaa loo dib u eegayaa',
    privacyLabel: 'Qarsoodi',
    submitAnonymously: 'Si qarsoodi ah u soo dir',
    submittingAnon: 'Si qarsoodi ah ayaa loo dirayaa',
    nameNotShared: 'Magacaagu LAMA wadaagi doono',
    nameVisibleToImam: 'Magacaagu Imaamka kaliya ayuu u muuqdaa',
    emailAddressLabel: 'Ciwaanka Emailka',
    emailOptionalDesc: '(ikhtiyaari — jawaab gaar ah)',
    emailPlaceholder: 'your@email.com',
    emailError: 'Fadlan gali ciwaanka emailka ee sax ah.',
    questionReceived: 'Su\'aasha Waa La Helay',
    yourQuestionLabel: 'Su\'aashaada',
    submittedAnonymously: 'Si qarsoodi ah ayaa loo diray — aqoonsigaagu si buuxda ayaa loo ilaaliyaa',
    preferInPerson: 'Ma doorbidaysaa si toos ah ula hadlida?',
    imamAvailable: "Imaamku waxa uu fulin karaa ka dib Jumu'ah iyo Cishe.",
    reviewedByImam: 'Imaamku si shakhsi ah ayuu u dib u eegayaa. Xog shakhsi ahi wax lama wadaago ama looma iibin.',
    sendingQuestion: 'Su\'aashaada ayaa la dirayaa…',
    footerQuickLinks: 'Xiriiriyaasha Degdega',
    footerPrayerTimes: 'Wakhtiyada Salaadda',
    footerContact: 'Xiriirka',
    footerDesc: 'Bulsho Islaamiyeed oo soo dhaweynaysa ee ku taal wadnaha Minneapolis, Minnesota.',
    footerApprox: '* Qiyaas · Bogga hore eeg wakhtiyada tooska ah',
    footerJumuahDesc: "Jimce kasta\nKhudbo 1:00 GD · Salaad 1:30 GD",
    footerCopyright: '© 2025 Umatul Islam Center · Dhammaan Xuquuqda Waa La Ilaaliyaa',
    footerPrivacy: 'Qaanuunka Qarsoodi',
    footerAccessibility: 'Helitaanka',
    loading: 'Waa la rarayo...',
    footer: '© 2025 Umatul Islam · Minneapolis, MN · Dhammaan Xuquuqda Waa La Ilaaliyaa',
    islamicGuidance: 'Hagida Islaamiga',
    commonQuestions: 'Su\'aalaha Caadiga ah',
    announcement: 'Xaaladda',
    preferSpeakDesc: "Imaamku waxa uu fulin karaa ka dib Jumu'ah iyo Cishe.",
  },
} satisfies Record<Lang, Record<string, string>>

export type TKey = keyof typeof translations.en

interface LangContextType {
  lang: Lang
  setLang: (l: Lang) => void
  t: (key: TKey) => string
  isRTL: boolean
}

const LangCtx = createContext<LangContextType>({
  lang: 'en',
  setLang: () => {},
  t: (k) => translations.en[k],
  isRTL: false,
})

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>('en')

  useEffect(() => {
    const stored = localStorage.getItem('ui-lang') as Lang | null
    if (stored && ['en', 'ar', 'so'].includes(stored)) setLangState(stored as Lang)
    else { setLangState('en'); localStorage.setItem('ui-lang', 'en') }
  }, [])

  const setLang = (l: Lang) => {
    setLangState(l)
    localStorage.setItem('ui-lang', l)
  }

  const t = (key: TKey): string => translations[lang][key] ?? translations.en[key]
  const isRTL = lang === 'ar'

  return (
    <LangCtx.Provider value={{ lang, setLang, t, isRTL }}>
      <div dir={isRTL ? 'rtl' : 'ltr'} lang={lang}>
        {children}
      </div>
    </LangCtx.Provider>
  )
}

export const useLang = () => useContext(LangCtx)
